# Set language to C++
language: cpp

# Choose os and clang versions
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

# Newer cmake
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

# Matrix evaluation
before_install:
    - eval "${MATRIX_EVAL}"

# Build
script:
  - cmake . && make
